# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "e02d1b2eb0b768913f5618b4b68ad0cb39d17e738c5e445c65824662da241f3192ec019ac8153465882475963b3584bf467171c5c945e096d2727b55d8e281ae";
      version = "1.0.371";

    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "700880bb9046ed12e5cb93a1c58b8f2184e674bd955908a2b83d8a5e376de7c213c2918ea6e93337aa7a54eb436f90d860f01d3098725f3b96605031f3e0f8a6";
      version = "2.5.1";

    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "a98e09e0f3c63d5004109c5b700a4ac4f1551ddc7731db1c5d439173c7a459c65d84378b0e980f8ff8de235dd480d8526610932a3cbb86fcf6516e1873682e68";
      version = "1.12.4";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljsjs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljsjs";
      groupId = "thheller";
      sha512 = "3d0b79eff075c38389d9f3501c60bf91a28a6ee25fc0a2df3159b365eff556e2ec8499b69860783478705ea33ff18e85fc0150229d5725e58e96f362bdc777f1";
      version = "0.0.22";

    };
    paths = [ src ];
  }

  rec {
    name = "javax.activation-api/javax.activation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.activation-api";
      groupId = "javax.activation";
      sha512 = "8ee0db43ae402f0079a836ef2bff5d15160e3ff9d585c3283f4cf474be4edd2fcc8714d8f032efd72cae77ec5f6d304fc24fa094d9cdba5cf72966cc964af6c9";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "da30a716770795fce390e4dd340a8b728f220c6572383ffef55bd5839655d5611fcc06128b2144f6cdcb36f53072a12ec80b04afee787665e7ad0b6e888a6787";
      version = "1.15";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "a99d68868959c7eef901f57dfb2069cc8be9313ecf67c7275eb2291231e344a3d7b8a184ede38780223acee51b9381897696912a02de58242c08164542c47830";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-test-display/com.bhauman";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-test-display";
      groupId = "com.bhauman";
      sha512 = "d8aafc0214bb3719adbb2c957e6a7c939e0db65a0bf69c4369654f736882c3203a4eeb66670e1da18f60faa8bf97b094712472ce883a5a1a5f8dd52b8e413d96";
      version = "0.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "d186fe9ac480ab7be989c6174d3931d1530856957177b1ee2794cb5ff6c4173467ff34c7e929e1a2b34d4b0e25abd7707f8d572db4c52e43c7218eac8822938f";
      version = "0.4.74";

    };
    paths = [ src ];
  }

  rec {
    name = "eql/edn-query-language";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "eql";
      groupId = "edn-query-language";
      sha512 = "36c57915d704ec4db147011cbb23b249f8c927bbfbc30bd7894bc042d0420ecac92a7ce8f15ddb374f61b6983189f0093217dffc8f8c7a17b21da889ce0970f5";
      version = "2025.09.27";

    };
    paths = [ src ];
  }

  rec {
    name = "undertow-core/io.undertow";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "undertow-core";
      groupId = "io.undertow";
      sha512 = "064b193b0037503144046274927782cfc9b317ec2794d6b2734238edc8a9ac865e97a8283449aefac8ddfc9972d49fd1827e14ca3a729f6775b94bb9d1c6a43d";
      version = "2.3.10.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "810832065897f33fd105aaf84984ee994ec5d90fe60d1a772b083bc2b1c59ff8e9e368bc0f456468824a65694f58cd47149f40b95488947ec5e5e96b44d44d1d";
      version = "0.9.0";

    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "2ac83d13ed607b19c1ca651ea54587bf502f0ee89ca042d0f79711e862ea83dbb5326db05523ede58529a258a3fa018e23363740c67b66c682aaf73260b23fab";
      version = "0.5.238";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "6ff7e8805c246e8c999b8d1da4ece0dc848dccf23d5beaac5327b891a00da000cc1cc5ef8d7025b38ea27969827a695c100eaa7e69fb77454361aa46f4c9f033";
      version = "1.1.230";

    };
    paths = [ src ];
  }

  (rec {
    name = "io.github.cognitect-labs/test-runner";
    src = fetchgit {
      name = "test-runner";
      url = "https://github.com/cognitect-labs/test-runner.git";
      rev = "dfb30dd6605cb6c0efc275e1df1736f6e90d4d73";
      sha256 = "17i8kn359qq016rg8gnq8b4s35y2pf6n0zcfkv5g8d69s7wmshrx";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "b69d16a14e6a9f712be8a8d985696fdb9316579c10286689277dca9c30f3f40a0d0416654841111f66b03302b6cc9fa90887d657bc181c122c33868790a8d5f0";
      version = "1.3.2";

    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-common/org.wildfly.common";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "wildfly-common";
      groupId = "org.wildfly.common";
      sha512 = "69c5aec2c4748038b81ee7f72ed48b64325a82ff754dabefb2c389cbc50246cc6183cd0033a08d6261aaeb521be91ca48a7c95d03a2ff2103608862d0bf7b732";
      version = "1.5.4.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "clara-rules/com.cerner";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clara-rules";
      groupId = "com.cerner";
      sha512 = "fe8f329ad938466dc9e7e60bafffb79373d601b0bc8682d479ff5b0f3a974ffeee72470e7aa3ee245b3227ffe322ce0f75f3c0919e1028b66d854b1671730ddb";
      version = "0.21.1";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "a8cb6bb4f23867fd79ca46619278aae1a53e9e171216d1cf7ed9ba157dbd6a0798e5440a080a2fc0a9498781598681ec4644dcf317bebefbf74bb6c9f47273d2";
      version = "0.8.280";

    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "98f10f546edbe75352aee5600870ac636dfd541472b3f54379b71157361e21154f0fcdcc137b01626e38ac55481ca03fbb2f482c845cbccc740ecb3bc1f3917e";
      version = "0.0-20250515-f04e4c0e";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljs";
      groupId = "thheller";
      sha512 = "c42c8bf923b933816aa70e4dbcf0bd495dc66c1fbc7f2a35ac08b8cfeaefed5210def3344048a07238e72f481ce0b80e6d83bc603d246aa381e676b2fda04b1f";
      version = "3.3.4";

    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "2d7c83194e4d3d2a8e45dc7b3542427e4876b0bdc40d7ea54cb52604eeed54265f9bda4cd89276441266058b3b8c7a30b47692e10df06023c3665c9711fbd7cf";
      version = "1.12.134";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "786778529435d8a14ab6ce2176cdf2b9ee6585a71893b785f26257122166dcefc7c4af3f612eda3974b06c16d06fc357178bf28b9b74010e9bc04c33221adc2f";
      version = "2.18.0";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.namespace/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.namespace";
      groupId = "org.clojure";
      sha512 = "4430c0d6f3974428cf99b51cd3d4ae6724401ef52257398f435dafd86dcc4294b706412f0abf9c8ac1d99eb8ab29b599210f2588df3f98ecef73651ca3088754";
      version = "1.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "d731e06ce832f7dc9f9788e73bf53f7c406ce6065fbac9f668b4cef38595b23810072fe2b39524dbc6a01ae91916214e1edd91619bf976006ddd18e88102617c";
      version = "0.6.27";

    };
    paths = [ src ];
  }

  rec {
    name = "jboss-logging/org.jboss.logging";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jboss-logging";
      groupId = "org.jboss.logging";
      sha512 = "60759c4340a7c1af0f10a5c2252e028150413d2437547f42018a94a838dc4a2bb24256411490a7e5f109b76305e2752ecf37def85e631d7e7b7e8461e0b54dda";
      version = "3.4.3.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "208953cf72691b3bab1ca2f9a045cccd3d75c46c90099ba884fbf16bc3e45045e5cd014d2c68c96e8a8826f87a5f0e18cb34b35e7ef03348953869c21e197367";
      version = "2.14.2";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload2-core/org.apache.commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload2-core";
      groupId = "org.apache.commons";
      sha512 = "b15fe7bb86110c96e8effca97b3de44191cb31aa50aec254cf171e5d714b60686936759336df25c248bbcdfce9c2e56561f03620770b626977a47a2d5ea16b47";
      version = "2.0.0-M2";

    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "876eac7406e60ab8b9bd6cd3c221960eaa53febea176a88ae02f4fa92dbcfe80a3c764ba390d96b909c87269a30a69b1ee037a4c642c2f535df4ea2e0dd499f2";
      version = "9.2";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-util/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-util";
      groupId = "thheller";
      sha512 = "803a068159276f5abf6d9cfa25f5c446c4c66d2eaec78393910cb2175b63a734c7c7effaf3064789608b1cf3899c287611c2d170fd78621193acc1fbbff1d5da";
      version = "0.7.0";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "bab8c657449a1d01e884923b77c5ef3d7a1a246c3ad1bd85a5b0c98b7952dbdeea97ce7d340ab50aa0dca647a1ef7eb846a52a1a4eecc55e1ff22145b8e820fe";
      version = "0.8.874";

    };
    paths = [ src ];
  }

  rec {
    name = "directory-watcher/io.methvin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "directory-watcher";
      groupId = "io.methvin";
      sha512 = "a2017f810e6059fd79041150e6a98c6a65ab1b47ca20f6c68bbfb37e6f8a61cbc2cfe85d084b8ff03b213d8b0ca4a6e9c67175a848c167d20992f03536b56298";
      version = "0.19.0";

    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "13d07c9f954764ebab18ea97fd7aac66ee08521d4db52bc986884b8cda942890012c2910ca438bde4070894eac79e1278f76d0479c46b32f0937e176501daec6";
      version = "0.0-20250515-f04e4c0e";

    };
    paths = [ src ];
  }

  rec {
    name = "hiccup/hiccup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "hiccup";
      groupId = "hiccup";
      sha512 = "034f15be46c35029f41869c912f82cb2929fbbb0524ea64bd98dcdb9cf09875b28c75e926fa5fff53942b0f9e543e85a73a2d03c3f2112eecae30fcef8b148f4";
      version = "1.0.5";

    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";

    };
    paths = [ src ];
  }

  rec {
    name = "xnio-nio/org.jboss.xnio";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xnio-nio";
      groupId = "org.jboss.xnio";
      sha512 = "d0dfb0617b671a97bbf7786e04ea7ead39816e1841cb74c53cf26fdb84e3d9440a3926d6e0b4741deae1792330e8ee6eb855e6de4f585db25670b636deaf93b3";
      version = "3.8.8.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "java.classpath/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java.classpath";
      groupId = "org.clojure";
      sha512 = "90cd8edeaea02bd908d8cfb0cf5b1cf901aeb38ea3f4971c4b813d33210438aae6fff8e724a8272d2ea9441d373e7d936fa5870e309c1e9721299f662dbbdb9a";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";

    };
    paths = [ src ];
  }

  rec {
    name = "jboss-threads/org.jboss.threads";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jboss-threads";
      groupId = "org.jboss.threads";
      sha512 = "3117f03857adc697064f89c28df1bb4553bfd676f4d5396dea5d95ae085a41488ac966aa8e4bde2a61049c8147ff3b03bb0ada6a1a149466b910fbc8dc50d86c";
      version = "3.5.0.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "a0aa547ec2f11221d1156c4388dea27bfd48470cc0da6dd3702e98530a3cdda146defb5309b5aea60770fb2282e329816ea6b6fbb4349eaf89b310df8003d733";
      version = "1.0.333";

    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "3520df744f250dbe061d1a5d7a05b7143f3a67a4c3f9ad87b8044ee68a36a702a0bcb3a203e35d380899dd01c28e01988b0a7af914b942ccbe0c35c9bdb22e11";
      version = "1.2.1";

    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler";
      groupId = "com.google.javascript";
      sha512 = "4898f1487a2760e374f4b42b664f52af7c6a4481a99008d0d56a8ce2a979edd18fd1afd5caccf3b5e1157bd4e99e1c4043ac527eaa5e7105aa88da35d311c534";
      version = "v20250407";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "65df7fe417fada187554a0a92d9f0b72972328e7943419066404dbf9443508b5ee156b844d15e3ebdca43de49d7c5fb853469bec44ca7b0dd0d693cf5b93de2a";
      version = "1.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-client/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-client";
      groupId = "thheller";
      sha512 = "e8019544a1cbbc9c3c9a931bd8dd9b7734260aca9d5e9a7a91089e898c65bee4ab535019c53b917f57c0aa49c1645296966226e4105b45463bbff2f30c7f427c";
      version = "1.4.0";

    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "8204b559d2704105741e1c9a5b8c639161a4f4af09e18b93d6af23685dd8bdebd66b64e626a4daa69069759c423640b3a3787216b78c2e62c891650e2269e8a0";
      version = "0.1.2";

    };
    paths = [ src ];
  }

  rec {
    name = "schema/prismatic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "schema";
      groupId = "prismatic";
      sha512 = "69e06dc40553dced3404d4fc4879cc00d237306404bd8f4d812d1c0f558d4183027248bc0a70c465ee3c9900253892d47aa2df1dec355e173dc447e4f8ce47fa";
      version = "1.1.6";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-websocket-protocols/org.ring-clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-websocket-protocols";
      groupId = "org.ring-clojure";
      sha512 = "be5239c275550c5522461c2489c2ed28ccfa725793f5d0d46808f2eb917591bb919c9303a3d8b2aa57c1e2843425337a50bc805b0e42f948b33a49ddcb644fd6";
      version = "1.14.1";

    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "4430da47874ce0cbeb22d46141d6c8c352efb7a5bd100aceba1279964d063cfe850998c79d0bfaaa674ca93a47bcdc2bc5dc8f62f7224d9fbf461e00fcba58fc";
      version = "1.0.1";

    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-client-config/org.wildfly.client";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "wildfly-client-config";
      groupId = "org.wildfly.client";
      sha512 = "3f442478c57f7dfac7039f6c7ae014bb2d45cdbd690ee631a3349edbca414adfe1984d065d1439f9b1546fa15fbd032c3a6bfe008f1ad50eef74201467b9f55f";
      version = "1.0.1.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "jna/net.java.dev.jna";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jna";
      groupId = "net.java.dev.jna";
      sha512 = "d9e1a9c4bea6b2d8aac9601d097a77013fd323b6f5c61d83fac2198ab6a988b5cf21390618933b143de4cc256d84bd2a86798fcb3679479ccfc6aecb20341984";
      version = "5.16.0";

    };
    paths = [ src ];
  }

  rec {
    name = "core.match/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.match";
      groupId = "org.clojure";
      sha512 = "8917aaa301eb1be71e4782f500dee6ee7dd7abc5b8c348958932872b81b70da1265951ae55dcf651d65f7296c3bca6cd2d6c5668a875821ede5fa331f2e925bf";
      version = "1.0.1";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "c640805f1e3b4b9cd391bac11eb613421e4fe1e3d4e8a01e15a5be1535fc7690d0482e4c7b6789b499cd3b5a123d74054659d529c9f3c9a4e527fefdf40d25a4";
      version = "1.5.2";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-core-protocols/org.ring-clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core-protocols";
      groupId = "org.ring-clojure";
      sha512 = "99e5d44480a1c01855ca5bb7cee8e2af643bcb36bb211ea734c3ff38cea7168bba77a0f19bb93eef06c49c5ed9e6dc58477740f41cc0e6c26408b6bc5d1a9560";
      version = "1.14.1";

    };
    paths = [ src ];
  }

  rec {
    name = "medley/dev.weavejester";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "medley";
      groupId = "dev.weavejester";
      sha512 = "6073f86c51a965b675db0798f32013e1d964d5ba21f51d73c1d7abac967ddef1374bb62524a00eccfb3ac5e40e001ee87743fe03cf99c66dd012f4d1971e6c56";
      version = "1.7.0";

    };
    paths = [ src ];
  }

  rec {
    name = "nrepl/nrepl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "3471ec735fb294d9dbbf5806213cfb9359a76870d2a018645701490eda70c76342e7bf21190ac65702557fbea3af92270224549209cf4b03a8e12299d01d7f44";
      version = "1.3.1";

    };
    paths = [ src ];
  }

  rec {
    name = "slf4j-api/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slf4j-api";
      groupId = "org.slf4j";
      sha512 = "f9b033fc019a44f98b16048da7e2b59edd4a6a527ba60e358f65ab88e0afae03a9340f1b3e8a543d49fa542290f499c5594259affa1ff3e6e7bf3b428d4c610b";
      version = "1.7.36";

    };
    paths = [ src ];
  }

  rec {
    name = "xnio-api/org.jboss.xnio";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xnio-api";
      groupId = "org.jboss.xnio";
      sha512 = "c1cc2d16c7b20106ebf7f1d50ae8b38d1d9e566c4c79880ada110c1a963ecf1c4845110addd5b369a6b9d3fbe9b3c76253d2050c159c517f9aa0ff589f5c7e94";
      version = "3.8.8.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "9441e7d0d61fb1665929a32464d8bacb5c4e9bbef062eb7fc72e39e7402e0bfd32fda4cf05df0c82c60f06936ba152cb73b42d79993ff146c1084640f4205124";
      version = "1.1.266";

    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "b90a9a049c6dc0274286e44bcc52bd231065161612eaff920381f3d41bbb28ae22771831ddd03b32e52d089c83ca8a6df6d1d3044977c287f040aaa713b5dc6d";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "piggieback/cider";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "piggieback";
      groupId = "cider";
      sha512 = "0f2e70002ef02568125c78c14266d23f43fb0ad477d05db697c0cc13b707bc1a0eacdce0f065f0eaaa68caffc3fb71384499ece45859f07fb1e6bc6d334bf86e";
      version = "0.6.0";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-undertow/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-undertow";
      groupId = "thheller";
      sha512 = "e5a8423b749d3818232993a214e9384f8a411d183674b51d09e1da53abe28030d989dccaf0cda21bfc44d0247dcf2c2dbba583dacd8eacf4dd308915a8d32445";
      version = "0.3.4";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "0ae4621e2c8e42a691b5d66753ab6fe0eb663db38c741d115fa3a6fb69f0bf039d7e54f98f016dd1c959c686b9ffa2c8af5d67a7656e03ff579638b62db3a583";
      version = "1.14.1";

    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "db8044d17fe8f45ced70f38d1b91f95d2bddfaf3512fa53273c50576c6324cb2df72174fce3d9fce1d5b19da7bdd9e7a00f31359472515d554a6d5414016b5c8";
      version = "1.1.234";

    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "da1de9e69c033c0fc9aeb17b7aa63c88a4f2614d65ef1ce2e0f83ce377168fc4fb1124653cad101d441cb1173f91cb1b0b8c190cd48dbd044d01d185d087efb2";
      version = "1.8.741";

    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "1d9e270e7ae1ab6bf3ad8c85b044096a58716180daeb9ffa181230b1d8862812954d4d2d3162b24cb2f1c947e998a186581259094e05ad875416488ca7dc3932";
      version = "2.4.0-b180830.0359";

    };
    paths = [ src ];
  }

  rec {
    name = "clara-eav/clyfe";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clara-eav";
      groupId = "clyfe";
      sha512 = "8db7cd0d9ad65f46cd593206c4e9646136ba21f56f50955b231ab6bc92153be28e238cecd4d832c11aa6c5c30f4986ea1230d29f2c21fbfacd875e14eca14787";
      version = "0.1.9";

    };
    paths = [ src ];
  }

  ];
  }
  